version: "2.1"

services:
  node:
    build: .docker/
    image: sboudfor/angular-cli
    ports:
      - 4200:4200
    volumes:
      - ./apps/:/src/

  mysql:
    image: mysql
    restart: always
    ports:
      - "3308:3306"
    volumes:
      - ./db-planner/:/var/lib/mysql/
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: planner

  client: 
     image: mysql
     depends_on:
      - mysql
     command: mysql -uroot -proot -hmysql planner

